inherit_from:
  - .rubocop_airbnb.yml

 # 検索方法$ bundle exec rubocop --require rubocop-airbnb
 
#コード解析しない内容
AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'path/ruby'